FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y \
    tcpdump \
    libpcap-dev \
    iproute2 \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    scapy \
    netifaces \
    ipaddress

RUN chmod +x /app/*.py

ENV INTERFACE=eth0

CMD ["python3", "q4-2-deteccao-arp.py"]
